tailwind.config = {
          darkMode: "class",
          theme: {
            extend: {
              "colors": {
                      "on-tertiary-container": "#ffe5db",
                      "surface-tint": "#006a63",
                      "background": "#f7faf8",
                      "tertiary-container": "#9c573a",
                      "primary": "#005c55",
                      "on-tertiary": "#ffffff",
                      "on-secondary-fixed-variant": "#003ea8",
                      "inverse-surface": "#2d3130",
                      "error-container": "#ffdad6",
                      "surface-container-lowest": "#ffffff",
                      "on-primary-fixed": "#00201d",
                      "on-tertiary-fixed-variant": "#72361b",
                      "surface-dim": "#d7dbd9",
                      "on-secondary": "#ffffff",
                      "secondary-fixed-dim": "#b4c5ff",
                      "tertiary-fixed": "#ffdbce",
                      "on-background": "#181c1c",
                      "primary-fixed": "#9cf2e8",
                      "outline": "#6e7977",
                      "secondary": "#0051d5",
                      "surface-container-highest": "#e0e3e1",
                      "outline-variant": "#bdc9c6",
                      "surface-variant": "#e0e3e1",
                      "on-primary": "#ffffff",
                      "surface": "#f7faf8",
                      "on-error": "#ffffff",
                      "primary-fixed-dim": "#80d5cb",
                      "tertiary-fixed-dim": "#ffb598",
                      "secondary-fixed": "#dbe1ff",
                      "on-primary-fixed-variant": "#00504a",
                      "error": "#ba1a1a",
                      "on-surface-variant": "#3e4947",
                      "on-error-container": "#93000a",
                      "tertiary": "#7f4025",
                      "surface-container-high": "#e5e9e7",
                      "primary-container": "#0f766e",
                      "surface-container": "#ebefed",
                      "inverse-on-surface": "#eef1f0",
                      "on-secondary-container": "#fefcff",
                      "secondary-container": "#316bf3",
                      "surface-container-low": "#f1f4f3",
                      "on-primary-container": "#a3faef",
                      "inverse-primary": "#80d5cb",
                      "on-surface": "#181c1c",
                      "on-secondary-fixed": "#00174b",
                      "on-tertiary-fixed": "#370e00",
                      "surface-bright": "#f7faf8"
              },
              "borderRadius": {
                      "DEFAULT": "0.25rem",
                      "lg": "0.5rem",
                      "xl": "0.75rem",
                      "full": "9999px"
              },
              "spacing": {
                      "container-max": "1200px",
                      "stack-lg": "32px",
                      "stack-md": "16px",
                      "stack-sm": "8px",
                      "base": "4px",
                      "gutter": "24px",
                      "section-gap": "80px",
                      "margin-desktop": "40px",
                      "margin-mobile": "16px"
              },
              "fontFamily": {
                      "headline-xl": ["Plus Jakarta Sans"],
                      "body-lg": ["Inter"],
                      "code-block": ["JetBrains Mono"],
                      "headline-md": ["Plus Jakarta Sans"],
                      "headline-lg": ["Plus Jakarta Sans"],
                      "body-sm": ["Inter"],
                      "headline-xl-mobile": ["Plus Jakarta Sans"],
                      "body-md": ["Inter"],
                      "label-mono": ["JetBrains Mono"]
              },
              "fontSize": {
                      "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                      "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                      "code-block": ["14px", { "lineHeight": "1.7", "fontWeight": "400" }],
                      "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "700" }],
                      "headline-lg": ["30px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                      "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
                      "headline-xl-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                      "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
                      "label-mono": ["13px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }]
              }
            }
          }
        }